### ISSUE TITLE
Registration fails when registration lock is enabled for the number

### ISSUE THREAD

**Issue by NotTheRealJoe** [AsamK/signal-cli#124]
signal-cli does not ask for the registration lock PIN, registration fails with code 423.

**Comment by AsamK** [comment]
I've implemented the registration lock PIN now in e057743232c0cae1401ba01a0ed1fdcd1c6ba5e0.
Use the `--pin` parameter to pass the PIN for verification. The commands `setPin` and `removePin` can be used to mange the PIN.
`signal-cli +NUMBER verify --pin PIN_CODE VERIFICATION_CODE`

**Comment by Sheloma** [comment]
i tried to verify with pin and i still get an error

here is what i did

1) signal-cli -u MYPHONENUMBER register
got a SMS with verification code.

2) signal-cli -u MYPHONENUMBER verify --pin PIN_HERE VERIFICATION_CODE_HERE
I got the following error
Verification failed! This number is locked with a pin. Hours remaining until reset: 153
Use ‘–pin PIN_CODE’ to specify the registration lock PIN

what is wrong?

**Comment by AsamK** [comment]
see #268
