### ISSUE TITLE
Register and linking account

### ISSUE THREAD

**Issue by EatCroissant** [AsamK/signal-cli#1386]
System info: Ventura Версія 13.5.2 (22G91)

I get qr code for signal, then scan in from phone and always get this message:
```
 >signal-cli link -n "optional device name"
INFO  AccountHelper - The Signal protocol expects that incoming messages are regularly received.
Link request error: StatusCode: 409
```

Also get error when try to register account
```
>./signal-cli -a +48*** register
java.lang.NullPointerException: Cannot invoke "org.whispersystems.signalservice.api.groupsv2.GroupsV2Operations.getProfileOperations()" because "groupsV2Operations" is null
```

Also register fail with error with captcha when variables (XDG_DATA_HOM &  XDG_RUNTIME_DIR) are set
```
Failed to register: StatusCode: 429 (RegistrationRetryException)
org.whispersystems.signalservice.api.push.exceptions.RegistrationRetryException: StatusCode: 429
```

**Comment by AsamK** [comment]
I've made a fix for the second error (81d2e315e3ceebddf33fd5e0c62f04cf7851aa29)
Can you provide a verbose log (`-v`) for the first and third error?

**Comment by EatCroissant** [comment]
First: 
```

█████████████████████████████████████████████
2023-11-21T13:02:18.848+0100 [main] INFO  LibSignal - [WebSocketConnection]: [provisioning:1520267010] disconnect()
2023-11-21T13:02:18.863+0100 [main] INFO  o.a.s.m.i.ProvisioningManagerImpl - Received link information from +48***, linking in progress ...
2023-11-21T13:02:19.003+0100 [OkHttp https://chat.signal.org/...] INFO  LibSignal - [WebSocketConnection]: [provisioning:1520267010] onClosing()
2023-11-21T13:02:19.003+0100 [OkHttp https://chat.signal.org/...] INFO  LibSignal - [WebSocketConnection]: [provisioning:1520267010] onClose()
2023-11-21T13:02:19.049+0100 [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Starting...
2023-11-21T13:02:19.219+0100 [main] INFO  com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Added connection org.sqlite.jdbc4.JDBC4Connection@46cf05f7
2023-11-21T13:02:19.222+0100 [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Start completed.
2023-11-21T13:02:19.255+0100 [main] INFO  o.a.s.manager.helper.AccountHelper - The Signal protocol expects that incoming messages are regularly received.
2023-11-21T13:02:20.453+0100 [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Shutdown initiated...
2023-11-21T13:02:20.454+0100 [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Shutdown completed.
2023-11-21T13:02:20.494+0100 [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-2 - Starting...
2023-11-21T13:02:20.495+0100 [main] INFO  com.zaxxer.hikari.pool.HikariPool - HikariPool-2 - Added connection org.sqlite.jdbc4.JDBC4Connection@254f906e
2023-11-21T13:02:20.495+0100 [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-2 - Start completed.
2023-11-21T13:02:20.700+0100 [main] DEBUG o.a.s.m.i.ProvisioningManagerImpl - Finishing new device registration
2023-11-21T13:02:21.431+0100 [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-2 - Shutdown initiated...
2023-11-21T13:02:21.432+0100 [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-2 - Shutdown completed.
Link request error: StatusCode: 409
org.whispersystems.signalservice.internal.push.exceptions.MissingCapabilitiesException: StatusCode: 409
        at org.whispersystems.signalservice.internal.push.PushServiceSocket.lambda$static$0(PushServiceSocket.java:509)
        at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceRequest(PushServiceSocket.java:2011)
        at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceRequest(PushServiceSocket.java:1949)
        at org.whispersystems.signalservice.internal.push.PushServiceSocket.finishNewDeviceRegistration(PushServiceSocket.java:503)
        at org.whispersystems.signalservice.api.SignalServiceAccountManager.finishNewDeviceRegistration(SignalServiceAccountManager.java:743)
        at org.asamk.signal.manager.internal.ProvisioningManagerImpl.finishDeviceLink(ProvisioningManagerImpl.java:148)
        at org.asamk.signal.commands.LinkCommand.handleCommand(LinkCommand.java:46)
        at org.asamk.signal.commands.CommandHandler.handleProvisioningCommand(CommandHandler.java:25)
        at org.asamk.signal.App.handleProvisioningCommand(App.java:250)
        at org.asamk.signal.App.handleCommand(App.java:153)
        at org.asamk.signal.App.init(App.java:139)
        at org.asamk.signal.Main.main(Main.java:56)
```

Thrid:
```
2023-11-21T16:08:50.411+0100 [main] DEBUG org.asamk.signal.App - Starting signal-cli 0.12.4
2023-11-21T16:08:50.514+0100 [main] INFO  LibSignal - [libsignal]: rust/bridge/jni/src/logging.rs:158: Initializing libsignal version:0.32.1
2023-11-21T16:08:50.825+0100 [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Starting...
2023-11-21T16:08:50.942+0100 [main] INFO  com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Added connection org.sqlite.jdbc4.JDBC4Connection@7e7b159b
2023-11-21T16:08:50.943+0100 [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Start completed.
2023-11-21T16:08:53.352+0100 [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Shutdown initiated...
2023-11-21T16:08:53.355+0100 [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Shutdown completed.
Failed to register: StatusCode: 429 (RegistrationRetryException)
org.whispersystems.signalservice.api.push.exceptions.RegistrationRetryException: StatusCode: 429
        at org.whispersystems.signalservice.internal.push.PushServiceSocket$RegistrationCodeRequestResponseHandler.handle(PushServiceSocket.java:2841)
        at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeServiceRequest(PushServiceSocket.java:2011)
        at org.whispersystems.signalservice.internal.push.PushServiceSocket.requestVerificationCode(PushServiceSocket.java:390)
        at org.whispersystems.signalservice.api.SignalServiceAccountManager.requestVoiceVerificationCode(SignalServiceAccountManager.java:296)
        at org.asamk.signal.manager.util.NumberVerificationUtils.requestVerificationCode(NumberVerificationUtils.java:93)
        at org.asamk.signal.manager.internal.RegistrationManagerImpl.register(RegistrationManagerImpl.java:121)
        at org.asamk.signal.commands.RegisterCommand.register(RegisterCommand.java:70)
        at org.asamk.signal.commands.RegisterCommand.handleCommand(RegisterCommand.java:46)
        at org.asamk.signal.commands.CommandHandler.handleRegistrationCommand(CommandHandler.java:31)
        at org.asamk.signal.App.handleRegistrationCommand(App.java:260)
        at org.asamk.signal.App.handleCommand(App.java:169)
        at org.asamk.signal.App.init(App.java:139)
        at org.asamk.signal.Main.main(Main.java:56)

```

**Comment by AsamK** [comment]
Thanks, for the first issue signal-cli needs to support a new capability, this needs some further investigation.

For the second issue you probably need to try to register with sms verification first before doing the voice verification, see https://github.com/AsamK/signal-cli/issues/1202

**Comment by EatCroissant** [comment]
I'm trying to make normal registration in second case. It is full command I have used. I need just to use any account because there is no way I can use library.

**Comment by AsamK** [comment]
I've released a new version yesterday, with a fix for the error in the secand case.

**Comment by EatCroissant** [comment]
It fix issue with variables, but I still can't register or link account 
Seems like error is similar to https://support.signal.org/hc/en-us/articles/360007211952-Troubleshooting-Installs-or-Updates
I will try to use another devices and check is error will be repeated on another versions. 
My ios version is 15.7.9 
I also tried to use bbernhard/signal-cli-rest-api like interface and link account but there was the same error.

**Comment by RichardFevrier** [comment]
Same `org.whispersystems.signalservice.internal.push.exceptions.MissingCapabilitiesException` here.
Funny thing is that with some iPhones it works (tested with `0.11.11` & `0.12.5`) and some others it doesn't (same iOS version, same Signal client / server versions).

**Comment by BouncySteak** [comment]
Still having the same issue with the --voice option

```
signal-api@59a64624fda5:/$ signal-cli --config /home/.local/share/signal-cli/ -a +xxxxxxxxx register --voice --captcha signalcaptcha://xxxxxxxxxx
Failed to register: StatusCode: 429 (RegistrationRetryException)
signal-api@59a64624fda5:/
```

Registers just find without it, but I am trying to register a phone that does not receive sms.

**Comment by kushaldas** [comment]
> Still having the same issue with the --voice option
> 
> ```
> signal-api@59a64624fda5:/$ signal-cli --config /home/.local/share/signal-cli/ -a +xxxxxxxxx register --voice --captcha signalcaptcha://xxxxxxxxxx
> Failed to register: StatusCode: 429 (RegistrationRetryException)
> signal-api@59a64624fda5:/
> ```
> 
> Registers just find without it, but I am trying to register a phone that does not receive sms.

I am having the same error but without the voice here.

**Comment by disaster123** [comment]
I'm trying todo a startChangeNumber - but i'm having the same issue:
```
linuxbox ~ # ./signal-cli -a "+yyy" startChangeNumber "+xxx" --voice 
Failed to change number: StatusCode: 429 (RegistrationRetryException)
linuxbox ~ # ./signal-cli -a "+yyy" startChangeNumber "+xxx"
Failed to change number: StatusCode: 429 (RegistrationRetryException)
```

**Comment by muad-dumb** [comment]
was unregistered via Signal CLI (still working on my phone) because I needed to upgrade CLI. within the upgraded folder i am attempting to register, but it isn't telling me the proper syntax, just pieces of it. as best i can tell what it wants me to do is:

./signal-cli -a register PHONENUMBER --captcha CAPTCHA 

(CAPTCHA being what is copied from the "Open Signal" link, but then no other instructions are given) i've done this, and am always returned "unrecognized argument --captcha". 

what is the exacty syntax needed to complete this process?

**Comment by BouncySteak** [comment]
`./signal-cli -a PHONENUMBER register --captcha CAPTCHA`
