### ISSUE TITLE
Error while running json method 'startLink'.

### ISSUE THREAD

**Issue by pnearing** [AsamK/signal-cli#1408]
Hi, with version signal-cli 0.12.6, running the json method 'startLink', throws an error:

orangepi@smoke:~/.cliSignal$ /usr/bin/signal-cli --verbose --log-file /home/orangepi/.cliSignal/signal-cli.log --config /home/orangepi/.cliSignal/signal-cli jsonRpc
{"jsonrpc": "2.0", "id": 0, "method": "startLink"}
ERROR SignalJsonRpcDispatcherHandler - Command execution failed
java.lang.AssertionError: org.signal.libsignal.zkgroup.InvalidInputException: Deserialization failure in zkgroup
        at org.whispersystems.signalservice.api.groupsv2.ClientZkOperations.create(ClientZkOperations.java:33)
        at org.asamk.signal.manager.internal.ProvisioningManagerImpl.<init>(ProvisioningManagerImpl.java:79)
        at org.asamk.signal.manager.SignalAccountFiles.initProvisioningManager(SignalAccountFiles.java:143)
        at org.asamk.signal.manager.internal.MultiAccountManagerImpl.getNewProvisioningManager(MultiAccountManagerImpl.java:116)
        at org.asamk.signal.manager.internal.MultiAccountManagerImpl.getNewProvisioningDeviceLinkUri(MultiAccountManagerImpl.java:104)
        at org.asamk.signal.commands.StartLinkCommand.handleCommand(StartLinkCommand.java:30)
        at org.asamk.signal.commands.StartLinkCommand.handleCommand(StartLinkCommand.java:15)
        at org.asamk.signal.jsonrpc.SignalJsonRpcCommandHandler$MultiCommandRunnerImpl.handleCommand(SignalJsonRpcCommandHandler.java:180)
        at org.asamk.signal.jsonrpc.SignalJsonRpcCommandHandler.parseParamsAndRunCommand(SignalJsonRpcCommandHandler.java:261)
        at org.asamk.signal.jsonrpc.SignalJsonRpcCommandHandler.runCommand(SignalJsonRpcCommandHandler.java:209)
        at org.asamk.signal.jsonrpc.SignalJsonRpcCommandHandler.handleRequest(SignalJsonRpcCommandHandler.java:67)
        at org.asamk.signal.jsonrpc.SignalJsonRpcDispatcherHandler.lambda$handleConnection$4(SignalJsonRpcDispatcherHandler.java:137)
        at org.asamk.signal.jsonrpc.JsonRpcReader.handleRequest(JsonRpcReader.java:138)
        at org.asamk.signal.jsonrpc.JsonRpcReader.handleMessage(JsonRpcReader.java:87)
        at org.asamk.signal.jsonrpc.JsonRpcReader.lambda$readMessages$0(JsonRpcReader.java:73)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1589)
Caused by: org.signal.libsignal.zkgroup.InvalidInputException: Deserialization failure in zkgroup
        at org.signal.libsignal.internal.Native.ServerPublicParams_CheckValidContents(Native Method)
        at org.signal.libsignal.zkgroup.ServerPublicParams.<init>(ServerPublicParams.java:14)
        at org.whispersystems.signalservice.api.groupsv2.ClientZkOperations.create(ClientZkOperations.java:31)
        ... 19 common frames omitted
{"jsonrpc":"2.0","error":{"code":-32603,"message":"org.signal.libsignal.zkgroup.InvalidInputException: Deserialization failure in zkgroup","data":null},"id":0}

**Comment by AsamK** [comment]
Are you using the correct libsignal version (0.32.1) for you signal-cli version?

**Comment by pnearing** [comment]
After looking in to how to compile signal-cli myself, I find that this is probably the wrong place for this error.  This started happening when I upgraded using the signal-cli ubuntu repo. It appears that they have compiled the signal-cli-jre package with the wrong libsignal version.  Although if you could point me to the right place to report this, I haven't found it on my own at this point.  Thank you for your time.

**Comment by m-ueberall** [comment]
> […] using the signal-cli ubuntu repo. […] Although if you could point me to the right place to report this, I haven't found it on my own at this point.

If you're using a proper third-party repository (which one?), this usually requires a GPG key which you had to store somewhere below `/etc/apt/...`. In that case, the latter should normally include an e-mail address as well which you can look for using `gpg --list-packets /etc/apt/.../gpg-key-file | grep -i "user ID"`.

**Comment by pnearing** [comment]
> > […] using the signal-cli ubuntu repo. […] Although if you could point me to the right place to report this, I haven't found it on my own at this point.
> 
> If you're using a proper third-party repository (which one?), this usually requires a GPG key which you had to store >somewhere below `/etc/apt/...`. In that case, the latter should normally include an e-mail address as well which you can >look for using `gpg --list-packets /etc/apt/.../gpg-key-file | grep -i "user ID"`.

Found it thanks.

**Comment by morph027** [comment]
Hi!

Just got your mail :wink: 

This should have been fixed with version `v0.12.7+2`. I've also added tests to the build pipeline to prevent this kind of issue in the future.

**Comment by pnearing** [comment]
Hi morph, I just tried to update the version from the repository, I'm still showing version 0.12.6+1.  I guess I should note that I'm using the arm64 version of signal-cli-jre.  Thanks.

**Comment by morph027** [comment]
Probably related to this: https://github.com/bbernhard/signal-cli-rest-api/issues/248#issuecomment-1875770936

Can you post the output of

```bash
uname -m
dpkg --print-architecture
apt-cache policy signal-cli-jre
apt-cache policy | grep -A2 signal-cli
```

**Comment by pnearing** [comment]
uname -m: aarch64

dpkg --print-architecture: arm64

apt-cache policy signal-cli-jre:
    signal-cli-jre:
      Installed: 0.12.6+1
      Candidate: 0.12.6+1
      Version table:
     *** 0.12.6+1 500
            500 https://packaging.gitlab.io/signal-cli signalcli/main arm64 Packages
            100 /var/lib/dpkg/status

apt-cache policy | grep -A2 signal-cli:
        500 https://packaging.gitlab.io/signal-cli signalcli/main arm64 Packages
             release o=morph027,a=signalcli,n=signalcli,l=signalcli,c=main,b=arm64
             origin packaging.gitlab.io

**Comment by morph027** [comment]
Thanks for the output, i've found the issue. The pipeline was missing some requirements so the repo step did not include the new jre packages

![image](https://github.com/AsamK/signal-cli/assets/600106/26a32085-ee7b-4b70-acfd-520ac62efca3)

Will fix this and create a new release `v0.12.7+3`

**Comment by pnearing** [comment]
Awesome, Thank you very much for your help. I'm developing a curses based client, this will let me get back to development.
