### ISSUE TITLE
Recurrent warning "Found X records that were deleted remotely"

### ISSUE THREAD

**Issue by Lukom** [AsamK/signal-cli#1883]
I receive such warning:

```
WARN  StorageHelper - Found 1 records that were deleted remotely but only marked unregistered locally. Removed those from local store.
```

every 5-20 seconds. If Signal Desktop is in foreground warnings are spammed more frequently. If you close Signal Desktop – there are no warnings. If you remove data and relink signal-cli – warnings disappear, but after some time appear again. It's reproduced on several latest instances of signal-cli (0.13.22) with Signal Desktop on MacOS and Windows.

Although these warnings do not harm they are just annoying and they spam logs. Also they are the sign that something not right, maybe synchronization is triggered too often because of some sync issue.

**Comment by AsamK** [comment]
Can you provide a verbose log of when this happens (`-vv`)? Especially the lines with `[Local Update]` and `[Remote Update]` would be interesting.
I just fixed one issue that would trigger this behavior (5fafa249744dd3cd44cd484d51893bb596d0edff) but there could be more cases where signal-cli is creating storage records slightly differently than Signal Desktop.

**Comment by Lukom** [comment]
No problem – here is a verbose log for 15 seconds – https://gist.github.com/Lukom/43e86927e9f10b889cf60852e7ef5748 , you can find message `Found 1 records that were ...` 4 times. I hope this helps.

**Comment by AsamK** [comment]
I've pushed a potential fix. Can you try again with the latest development build?
https://github.com/AsamK/signal-cli/actions/runs/20110811884

**Comment by Lukom** [comment]
I've tried build [signal-cli-archive-21](https://github.com/AsamK/signal-cli/actions/runs/20110811884/artifacts/4829077328) but it didn't help – I still see recurrent warnings.

**Comment by AsamK** [comment]
Can you provide another log?

**Comment by Lukom** [comment]
Oh, right, sure! Here it is: https://gist.github.com/Lukom/794a453add46b4d2abb9e1c10883bab0

**Comment by AsamK** [comment]
I pushed some fixes, that should fix this continues sync issue.
