### ISSUE TITLE
Starting version 0.6.8, signal-cli daemon throws DBusException

### ISSUE THREAD

**Issue by matthew-piziak** [AsamK/signal-cli#315]
`org.freedesktop.dbus.exceptions.DBusException: Failed to connect to bus: Failed to auth`

This does not happen on version 0.67.

**Comment by AsamK** [comment]
which operation system are you using?

**Comment by matthew-piziak** [comment]
I'm using NIxOS. Is there any specific environment information that I should look for?

**Comment by noonien** [comment]
Happens to me also, also on NixOS

**Comment by matthew-piziak** [comment]
I can reproduce on `0.6.10`. I am sticking on `0.6.7` for now, but unfortunately cannot receive attachments anymore, presumably because of a protocol mismatch.

**Comment by matthew-piziak** [comment]
Legacy groups are no longer working on version `0.6.7`. I am able to receive messages from some users but not others, and I am not able to send messages to the group.

**Comment by matthew-piziak** [comment]
I've stopped using DBUS and instead started looping `signal-cli` into a queue. This allowed me to upgrade to version `0.6.10`. I do look forward to DBUS being usable eventually though, and will gladly help test changes on this platform.

**Comment by dotlambda** [comment]
I can also reproduce on NixOS.
cc @ivan @erictapen

**Comment by johnfreed** [comment]
@matthew-piziak and @AsamK, it appears that this issue has been fixed:

https://github.com/NixOS/nixpkgs/pull/72829

**Comment by AsamK** [comment]
I've updated signal-cli to use the hypfview dbus-java 4.0 beta, which uses native java unix sockets, that should resolve at least some dbus issues.
If you still have issues with dbus, please open an issue on the [dbus-java project](https://github.com/hypfvieh/dbus-java)
If there are some known workarounds or additional steps, feel free to add it to the wiki: https://github.com/AsamK/signal-cli/wiki/DBus-service

**Comment by matthew-piziak** [comment]
Thanks @AsamK! ISsue persists on signal-cli 0.9.2. I'll take a look upstream.

**Comment by AsamK** [comment]
The new dbus integration is not part of a released signal-cli version yet.
You could test it with the latest master build: https://github.com/AsamK/signal-cli/actions/runs/1493670866

**Comment by matthew-piziak** [comment]
Oh, I see, thanks! I ran into some linker problems when I tried to build and I'm okay with polling the non-dbus API for now, so I'll try again when the new version is released.

**Comment by matthew-piziak** [comment]
I'm pleased to report that as of signal-cli 0.10.2, this issue no longer occurs!
