### ISSUE TITLE
listGroups has no output

### ISSUE THREAD

**Issue by makeworld-the-better-one** [AsamK/signal-cli#438]
I am using signal-cli 0.7.2 and have been able to successfully send and receive messages after linking it to my phone. But running `signal-cli -u NUMBER listGroups` runs for a bit, then exits with no output. Same when I used the `-d` flag.

I suppose it's possible this is related to Signal's ongoing issues. But my app is working fine and no longer has the banner, and as I said before, I can send and receive messages with signal-cli fine.

**Comment by AsamK** [comment]
there's an issue in the current version (already fixed in master), that the initial group sync is not saved correctly. When you receive group messages those groups will then appear in the `listGroups` output.

**Comment by 4jwWa2EnYK5FIIaK7AVp** [comment]
With v0.7.4 the receive bug [https://github.com/AsamK/signal-cli/discussions/442](url) has been fixed, but this listGroups bug still exists for me with v1 groups. There's no output on the command line and the groupStore is not getting updated.

**Comment by makeworld-the-better-one** [comment]
I experienced this as well. I though that it was because Signal needs you to receive a message in those groups before you can see them, but actually maybe I'm wrong about that. So yes, I can confirm that the group output is still empty

@AsamK could you reopen this?

**Comment by AsamK** [comment]
try removing the signal-cli data file and linking again, then all v1 groups should be shown.
for v2 there's a new mechanism with encrypted remote storage, but that's not supported by signal-cli yet.

**Comment by 4jwWa2EnYK5FIIaK7AVp** [comment]
> try removing the signal-cli data file and linking again, then all v1 groups should be shown.
> for v2 there's a new mechanism with encrypted remote storage, but that's not supported by signal-cli yet.

Sadly, it is still not working after removing the data file and registering again. List groups output is empty, groupStore in the data file as well and I cannot send messages to groups. Although creating a group with updateGroup is working.
