### ISSUE TITLE
registerWithCaptcha fails with Dbus when config already exists

### ISSUE THREAD

**Issue by bublath** [AsamK/signal-cli#813]
Several of my users reported issues with 0.9.0 (and 0.9.2) that setting a Captcha via the Dbus Method does not work:
Error org.freedesktop.dbus.exceptions.DBusExecutionException: Error Executing Method org.asamk.Signal.registerWithCaptcha: null
while from the commandline (after stopping the service) it works as expected.

One reproducable scenario seems to be an already existing configuration for that number (after deleting the config data for this number, registration works). Can be reproduced using dbus-send.
However I also had one user where deleting the old config did not help, but again using plain signal-cli from commandline unblocked him.

**Comment by AsamK** [comment]
One issue with registering, when the account data already exists, is already fixed in the master branch. For the other one, it's hard to say what went wrong.

**Comment by bublath** [comment]
Unfortunately I cannot confirm this. When "re-registering" an existing number I still get the error with latest master and deleting the registry for the number helps.

**Comment by AsamK** [comment]
Is this existing account in a registered or unregistered state? If the account is already registered, registering it again won't work in multi-account daemon mode.
I've added some additional error messages in the master branch for this.

**Comment by bublath** [comment]
re-register in registered state is the way I reproduced the issue, though some of my user even seem to have problems with their initial registration.
I don't see a method in dbus to unregister. Can this be achieved somehow with the existing interface or could that be added?

**Comment by AsamK** [comment]
There's an unregister method in the dbus interface (only on master): https://github.com/AsamK/signal-cli/blob/861f47d734a2c416ca3231ad72f9f129da5a706f/src/main/java/org/asamk/Signal.java#L178
Registering an account in the unregistered state is what has been fixed in the master branch.

**Comment by bublath** [comment]
Thanks. I only checked the man-page where this method is not documented yet.
Most of my users are using Debian/Raspbian "buster" where Java17 is not available by "apt" and unlikely will upgrade in the near future, so I won't be able to verify/use this at the moment.
I probably need to think about enhancing my installer to ship a "private" Java17 version at some point (which works for me in my test environment).
